name: Build & Lint Witness Backend

on:
  push:
    paths:
      - 'witness-backend/**'
      - '.github/workflows/test-backend.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'yarn'
          cache-dependency-path: '**/yarn.lock'
      - name: Install dependencies
        working-directory: ./witness-backend/
        run: corepack enable && yarn install --frozen-lockfile
      
      - name: Install chalcedony-vcs deps
        working-directory: ./chalcedony-vcs
        run: yarn install --immutable

      - name: Build chalcedony-vcs
        working-directory: ./chalcedony-vcs
        run: yarn tsc

      - name: Lint
        working-directory: ./witness-backend/
        run: yarn lint

      - name: Test
        working-directory: ./witness-backend/
        run: yarn test