name: Build & Lint App

on:
  push:
    paths:
      - 'app/**'
      - '.github/workflows/test-app.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'yarn'
          cache-dependency-path: '**/yarn.lock'

      - name: Install app dependencies
        working-directory: ./app/
        run: corepack enable && yarn install --immutable

      - name: Lint
        working-directory: ./app/
        run: yarn run lint

      - name: Build
        working-directory: ./app/
        run: yarn run build